# -*- coding: utf-8 -*-
"""livingwageONSdata.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xKYTgT0dh-Bp2sAQ643CaXjuVPslNdBx
"""

# mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')

!pip3 install pyspark

from pyspark.sql import SparkSession
spark = SparkSession.builder.master("local[*]").appName('Living wage ONS data analysis').getOrCreate()

ons_df = spark.read.option("header", "true").csv("/content/drive/MyDrive/ONS data Living wage/ONSdata1.csv")

ons_df.show()

ons_df.select('Areaname').groupBy('Areaname').count().orderBy('count', ascending=False).show()

"""
**Percent earning less than London Living Wage (LLW) per hour for four random years**

```

```

"""

ons_df1=ons_df.select('Areaname','20052','20107','201512','201829')
ons_df1.show()

import pandas as pd
import matplotlib.pyplot as plt

#create data dictionary
df1 = pd.DataFrame({'summary': ['2005', '2010', '2015','2018'],
                   ' City of London': [ 2.9, 4, 6.4, 0.9],
                   'Bexley': [20.4, 24.3, 34.8 , 4.6],
                   'Ealing': [ 15.3, 16.8,26.6, 3.5],
                   'Hounslow': [17.4, 13.5,19.2, 3.4]})

index=['City of London','Bexley','Ealing','Hounslow']


#plot columns on bar chart
df1[['summary', ' City of London','Bexley','Ealing','Hounslow']].plot(x='summary', kind='bar',logy=False,figsize=(12,12))
plt.xticks(fontsize=16)
plt.yticks(fontsize=16)
plt.xlabel('Year', fontsize=18,color='black')
plt.ylabel('Data', fontsize=18,color='black')
plt.title('Percent earning less than London Living Wage (LLW) per hour',fontsize=20,color='black')
plt.legend(index,loc="upper right",fontsize=10,edgecolor='red')
plt.show()

ons_df = spark.read.option("header", "true").csv("/content/drive/MyDrive/ONS data Living wage/onsdata2.csv")

ons_df.show()

"""The estimated  % of employee jobs below the London living wage

"""

ons_df2=ons_df.select('_c0','Male employees%','Female employees%','Full-time males%','Full-time females%')
ons_df2.show()

import pandas as pd
import matplotlib.pyplot as plt

#create data dictionary
df1 = pd.DataFrame({'summary': ['2018', '2019', '2020','2021'],
                   ' Male employees%': [ 2.9, 4, 6.4, 0.9],
                   'Female employees%': [20.4, 24.3, 34.8 , 4.6],
                   'Full-time males%': [ 15.3, 16.8,26.6, 3.5],
                   'Full-time females%': [17.4, 13.5,19.2, 3.4]})

index=['Male employees%','Female employees%','Full-time males%','Full-time females%']


#plot columns on bar chart
df1[['summary', ' Male employees%','Female employees%','Full-time males%','Full-time females%']].plot(x='summary', kind='barh',logy=False,figsize=(12,12))
plt.xticks(fontsize=16)
plt.yticks(fontsize=16)
plt.xlabel('Data', fontsize=18,color='black')
plt.ylabel('Year', fontsize=18,color='black')
plt.title('The estimated  % of employee jobs below the London living wage',fontsize=20,color='black')
plt.legend(index,loc="upper right",fontsize=10,edgecolor='red')
plt.show()